import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { bootPi } from "./helpers/boot-pi.js";
import { makePiCopy, type PiCopy } from "./helpers/patch-harness.js";
import { applyCorePatch } from "../scripts/apply-core-patch.js";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

let copy: PiCopy;
describe("fullscreen composer/footer lifecycle", () => {
  beforeAll(() => { copy = makePiCopy(); applyCorePatch(copy.pkgDir); });
  afterAll(() => copy?.cleanup());
  it("streams, edits a draft, changes effort, resizes and settles without losing native controls", async () => {
    const term = await bootPi(30000, 15000, [], { package: true, skill: true }, undefined, copy.cli);
    try {
      expect(term.viewport.getText()).toContain("auto on");
      const initialEffort = term.viewport.getText().split("\n").find(row => row.includes(" effort "));
      term.press("Shift+Tab");
      await term.waitForStable(100, 3000);
      expect(term.viewport.getText().split("\n").find(row => row.includes(" effort "))).not.toBe(initialEffort);
      term.type("POLISH"); term.press("Enter");
      await term.waitFor("Inspecting the fixture", 5000);
      term.type("draft remains");
      await term.waitFor("A full-width answer", 5000);
      expect(term.viewport.getText()).toContain("● A full-width answer");
      expect(term.viewport.getText()).toContain("draft remains");
      term.resize(60, 30);
      await term.waitFor("Finished", 5000);
      expect(term.viewport.getText()).toContain("draft remains");
      expect(term.viewport.getText()).toContain("Ready");
      expect(term.viewport.getText()).toContain("● fake-model");
      const settled = term.viewport.getText();
      await new Promise(resolve => setTimeout(resolve, 150));
      expect(term.viewport.getText()).toBe(settled);
      term.press("Ctrl+U");
      term.type("POLISH"); term.press("Enter");
      await term.waitFor("Reasoning", 5000);
      term.press("Escape");
      await term.waitFor("Stopped", 5000);
      expect(term.viewport.getText()).not.toContain("Finished ·");
      term.resize(100, 30);
      term.type("/reload"); term.press("Enter");
      await term.waitFor("effort", 5000);
      await term.waitForStable(200, 5000);
      expect(term.viewport.getText()).not.toContain("Stopped ·");
      term.type("GROUPTOOLS"); term.press("Enter");
      await term.waitFor("Read 1 file", 5000);
      await term.waitFor("Finished", 5000);
      term.press("Ctrl+O");
      await term.waitFor("package.json", 5000);
      term.press("Ctrl+O");
      await term.waitFor("Read 1 file", 5000);
      expect(term.viewport.getText()).not.toContain("Tool output:");
      term.type("/reload"); term.press("Enter");
      await term.waitForStable(200, 5000);
      await term.waitFor("Read 1 file", 5000);
      term.resize(120, 36);
      term.type("RESTORE"); term.press("Enter");
      await term.waitFor("Read 2 files · ran 1 command", 10000);
      await term.waitFor("Finished", 5000);
      term.type("Keep the reasoning visible, but quieter than the answer.");
      await term.waitFor("› Keep the reasoning", 5000);
      const expanded = term.viewport.getText();
      const rows = expanded.split("\n");
      const commentary = rows.findIndex(row => row.includes("I'll inspect the footer"));
      expect(rows[commentary + 1]).toContain("Read 2 files · ran 1 command");
      expect(rows[commentary + 1].indexOf("Read")).toBe(rows[commentary].indexOf("I'll"));
      expect(expanded).toContain("› Keep the reasoning");
      term.click(rows[commentary + 1].indexOf("Read"), commentary + 1);
      await term.waitFor("restoration-fixture", 3000);
      term.press("Ctrl+O");
      term.press("Ctrl+O");
      await term.waitFor("Read 2 files · ran 1 command", 3000);
      await term.waitForStable(100, 3000);
      term.press("Ctrl+T");
      await term.waitFor("Thinking...", 5000);
      await term.waitForStable(100, 3000);
      const collapsed = term.viewport.getText();
      expect(collapsed).not.toContain("Thinking blocks:");
      if (process.env.REMOTICON_CAPTURE_DIR) writeFileSync(join(process.env.REMOTICON_CAPTURE_DIR, "restored-grid.json"), JSON.stringify({ cols: 120, rows: 36, expanded, collapsed }, null, 2));
      term.press("Ctrl+T");
      await term.waitFor("I need to separate", 5000);
      term.resize(80, 24);
      await term.waitForStable(100, 3000);
      expect(term.viewport.getText()).toContain("› Keep the reasoning");
      term.press("Ctrl+U");
      term.resize(120, 36);
      term.type("SKILLREAD"); term.press("Enter");
      await term.waitFor("Skill(sample-skill)", 5000);
      await term.waitFor("Successfully loaded skill", 5000);
      await term.waitFor("Finished", 5000);
      for (const [cols, height] of [[120, 36], [80, 24], [60, 30]]) {
        term.resize(cols, height);
        term.press("Ctrl+O");
        await term.waitForStable(100, 3000);
        expect(term.viewport.getText()).toContain("Skill(sample-skill)");
        expect(term.viewport.getText()).not.toContain("SKILL_SOURCE_MUST_STAY_HIDDEN");
      }
      term.type("/skill:sample-skill user argument retained"); term.press("Enter");
      await term.waitFor("user argument retained", 5000);
      await term.waitFor("Finished", 5000);
      term.press("Ctrl+O");
      await term.waitForStable(100, 3000);
      expect(term.viewport.getText()).toContain("Skill(sample-skill)");
      expect(term.viewport.getText()).not.toContain("SKILL_SOURCE_MUST_STAY_HIDDEN");
      term.type("/reload"); term.press("Enter");
      await term.waitForStable(200, 5000);
      expect(term.viewport.getText()).toContain("Skill(sample-skill)");
      expect(term.viewport.getText()).not.toContain("SKILL_SOURCE_MUST_STAY_HIDDEN");
    } finally { await term.close(); }
  });
});
